name: 'Dependency Check - Bom Dia Codigo'
description: 'Github action to execute dependency check for Bom Dia Codigo labs'
Author: 'javixeneize'
branding:
  icon: 'check-square'  
  color: 'red'
inputs:
    project:
        required: true
    path:
        required: true  
    format:
        required: true
    out:
        required: true
        default: 'reports'

    args:
        required: false
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:

        - '--project'
        - '${{ inputs.project }}'
        - '--scan'
        - '/github/workspace/${{ inputs.path }}'
        - '--format' 
        - '${{ inputs.format }}'
        - '--out'
        - '/github/workspace/${{ inputs.out }}'
        - '--noupdate'
        - ${{ inputs.args }}
